name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
#workflow fails at testing job due to unestablishment of MongoDB connection if these value are not passed.
env:      
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                nodejs_version: [18, 20]
                operating_system: [ubuntu-latest, macos-latest]
                exclude:
                    - nodejs_version: 18
                      operating_system: macos-latest
        runs-on: ${{ matrix.operating_system }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.nodejs_version }}
            
            - name: Install Dependencies
              run: npm install
            
            - name: Unit Testing
              id: node-unit-testing-step    
              run: npm test
          #If the above Unit Testing step fails(for example, failed test case or syntax error), the Archive Test Result step will be skipped. 
          #And you cannot debug the issue without seeing the test results but is is not available since this setp will be skipped in a failure scenario.
          #To overcome that, we can use expressions to to run Archive Test Result step always irrespective of above step's state
            - name: Archive Test Result
              if: steps.node-unit-testing-step.outcome == 'failure' || steps.node-unit-testing-step.outcome == 'success'
              uses: actions/upload-artifact@v3
              with:
                name: Mocha-Test-Result
                path: test-results.xml
    #Need to setup nodejs first since its a different job  ##runs in parallel with unit-testing job
    code-coverage:       
        name: Code-Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup NodeJS Version - 18
              uses: actions/setup-node@v3
              with:
                node-version: 18
            
            - name: Install Dependencies
              run: npm install

            - name: Check Code Coverage
              continue-on-error: true   #We want this job to be run even if the coverage is below the threshold
              run: npm run coverage

            - name: Archive Test Result
              uses: actions/upload-artifact@v4
              with:
                name: Code-Coverage-Result
                path: coverage
                retention-days: 5
